name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your deployment branch if needed
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./Twotter/server
        run: npm ci

      - name: Build Typescript
        working-directory: ./Twotter/server
        run: npm run build

      - name: Copy built tsc files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "server/dist/"
          target: "~/Twotter/server/dist/"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          HOSTNAME: ${{ secrets.SERVER_HOST }}
          USER_NAME: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" "
            cd ~/Twotter
            git pull origin main

            cd client
            echo 'VITE_API_URL=https://scoopty.club/api/v1' > .env.production
            npm install
            npm run build -- --mode production

            echo 'VITE_API_URL=https://scoopty.club/api/v1' > .env


            # Install dependencies for server
            cd ../server
            echo 'NODE_ENV=production' > .env
            npm install

            # DB Migrations
            npx drizzle-kit migrate up

            # Ensure frontend directory exists inside server (for serving static files)
            cd ../server
            mkdir -p ~/Twotter/server/public

            # Move React build (client/dist/) to server/public/
            rsync -av --delete ~/Twotter/client/dist/ ~/Twotter/server/public/


            # Restart Express server
            pm2 restart dist/index.js || pm2 start dist/index.js --name 'server'
            pm2 save
          "
