name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your deployment branch if needed
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Client (Vite React)
        run: |
          cd client
          echo 'VITE_API_URL=http://3.16.68.73:3000/api/v1' > .env.production
          npm install
          npm run build -- --mode production

      - name: Check .env.production
        run: |
          cd client
          echo "Contents of .env.production:"
          cat .env.production

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          HOSTNAME: ${{ secrets.SERVER_HOST }}
          USER_NAME: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" "
            cd ~/Twotter
            git pull origin main

            cd client
            echo 'VITE_API_URL=http://3.16.68.73:3000/api/v1' > .env


            # Install dependencies for server
            cd ../server
            echo 'NODE_ENV=production' > .env
            npm install

            # Install dependencies for client (if needed)
            cd ../client
            npm install

            # Ensure frontend directory exists inside server (for serving static files)
            cd ../server
            mkdir -p ~/Twotter/server/public

            # Move React build (client/dist/) to server/public/
            rsync -av --delete ~/Twotter/client/dist/ ~/Twotter/server/public/

            # Restart Express server
            pm2 restart index.js || pm2 start index.js --name 'server'
            pm2 save
          "
