name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your deployment branch if needed
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Twotter/server
            git pull origin main
            npm install
            pm2 restart index.js
